spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    org.springframework.batch: DEBUG
    org.springframework: DEBUG


---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local
---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  config:
    activate:
      on-profile: mysql
